### ISSUE TITLE
Possible bug in getTLSCertificate where err might not be returned

### ISSUE THREAD

**Issue by yangmarcyang** [spiffe/go-spiffe#174]
In v2/spiffetls/tlsconfig/config.go `getTLSCertificate` function, the `return nil, err` is put inside the `if trace.GotCertificate != nil` block. So, it sounds like a bug when trace.GotCertificate is not configured, where the error would not be returned and the following code would cause panic when dereferencing svid `s`.

Code pointer: [link](https://github.com/spiffe/go-spiffe/blob/7b2184ee742dec93be292cdf8cc06ac6fbffcdbd/v2/spiffetls/tlsconfig/config.go#L217)

If it is a real bug, the fix would look very simple: just move the return statement outside below the if block.

**Comment by azdagron** [comment]
That is a bug!

**Comment by azdagron** [comment]
You're suggested fix is spot on.

**Comment by yangmarcyang** [comment]
> Your suggested fix is spot on.

Thanks for the confirmation. I will create a PR then.

**Comment by azdagron** [comment]
Fixed by #175
