### ISSUE TITLE
use in own project

### ISSUE THREAD

**Issue by vtolstov** [spiffe/go-spiffe#18]
how to use this in own project if i want mTLS and spiffe?

**Comment by evan2645** [comment]
@vtolstov what would you like to see here? Is the godoc reference page good enough? Or you'd prefer something more detailed? Can you help with some examples of what you'd think is ideal?

https://godoc.org/github.com/spiffe/go-spiffe

**Comment by vtolstov** [comment]
this docs not helps. but i'm use go and write own mTLS CA server issuer and mTLS clients that uses it via jwt token.
