### ISSUE TITLE
Problem with SPIFFE trust domain usage during peer verification

### ISSUE THREAD

**Issue by srago** [spiffe/go-spiffe#201]
We've deployed a go-based service in GKE where the workload identity certificates are x509 certs with the SPIFFE identifier in the SAN and are used to implement mTLS connections.  Each service in the VPC has its own project, which means each service has a unique trust domain.  (Most of the services are java-based, so that probably explains why we were the first to see it.) Because the trust domains differ, the VerifyPeerCertificate() callback will fail when our go service is called.  It calls x509svid.ParseAndVerify(), which ends up calling x509svid.Verify(), which tries to find the trust bundle using the trust domain derived from the client's SPIFFE ID.  That always fails because the server doesn't have the client's trust bundle (nor should it, if I understand how this is supposed to work).  We fixed this by using the server's trust bundle if the call to GetX509BundleForTrustDomain() fails, because if the server and client share a common certificate authority, then the server should be able to verify the authenticity of the client's certificate (and if they don't share one, the verification will fail anyway).  Another thing we thought about was the authorizer check isn't taken into account in the verification until after the certificate verification succeeds.  If we want AuthorizeAny semantics, then the certificate verification probably needs to understand that, but maybe just using the server bundle is okay in all cases, because if the certificate is valid, the authorizer check will still fail the overall verification when stricter semantics are requested.  So are we misunderstanding how all of this is supposed to work or do you agree there is a problem here?

**Comment by azdagron** [comment]
I'm not quite sure I understood that fully but workloads that reside in different trust domains can only mutually authenticate if each party has the trust bundle for the peer's trust domain. In other words. If a service from trust domain A and a service from trust domain B want to mutually authenticate, then the service in A must have B's trust bundle. Likewise the service from B must have A's trust bundle. This is called [SPIFFE Federation](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Federation.md).

**Comment by srago** [comment]
The mapping of project ID to unique trust domain is a function of google cloud AFAICT.  The decision to have every team use a separate project ID is most likely our choice, and we end up with a bit of a disconnect in what we need to do and what the library does.  Anyway, I hadn't thought of implementing my own Source -- that's a good idea, thanks.
