### ISSUE TITLE
Update README to reflect current library state

### ISSUE THREAD

**Issue by evan2645** [spiffe/go-spiffe#22]
Lots of things have changed in this library since the README was written. Update the README to reflect the current state, and include some sample code for
* Starting a basic SPIFFE listener w/ WL API support
* Using a basic SPIFFE dialer w/ WL API support
* Anything else that the person picking up this issue thinks might be useful

**Comment by azdagron** [comment]
I think this is covered in the v2 README at https://github.com/spiffe/go-spiffe/tree/master/v2.
