### ISSUE TITLE
WithDefaultX509SVIDPicker / WithDefaultJWTSVIDPicker

### ISSUE THREAD

**Issue by nstott** [spiffe/go-spiffe#264]
is there any appetite to have a picker for JWT tokens, just as we have one for x509's?
something like this perhaps?
https://github.com/spiffe/go-spiffe/compare/main...nstott:go-spiffe:n/jwtpicker?expand=1

**Comment by kfox1111** [comment]
Seems like adding a picker would be ok.

**Comment by azdagron** [comment]
Agreed. I'd accept a PR for this.

**Comment by kfox1111** [comment]
The link is broken. This looks to be it though:
https://github.com/spiffe/go-spiffe/compare/main...nstott:go-spiffe:n/jwtpicker

**Comment by azdagron** [comment]
Yup, just need someone to turn that into a PR.

**Comment by azdagron** [comment]
Fixed in #301
