### ISSUE TITLE
Allow `workloadapi` backoff to be customized

### ISSUE THREAD

**Issue by strideynet** [spiffe/go-spiffe#269]
I'm writing a test suite and one frustration is that I'm in a place where I don't know exactly when the listener will be ready for the Workload API client to connect. At the moment, I start the unit under test and the client at the same time, and then wait for the client to succeed.

The current linear backoff behaviour means that this test takes much longer to run than it needs to, as the first few attempts fail and then the backoff is increased.

I'd like to suggest a new `ClientOption` which allows the Backoff behaviour to be customised. I'm happy to raise a PR for this.

**Comment by azdagron** [comment]
Thanks for raising this issue! This was implemented in #302.
