### ISSUE TITLE
Shouldn't this project be spiffe/go-svid?

### ISSUE THREAD

**Issue by ajessup** [spiffe/go-spiffe#6]
The scope of this client library seems to be the SVID rather than the SPIFFE project as a whole (which encompasess many APIs which may have their own Golang client libraries). As such, shouldn't we re-name it `go-spiffe`?

**Comment by mbyczkowski** [comment]
Given changes merged in #20, I think we can close this issue now.

**Comment by evan2645** [comment]
Thank you @mbyczkowski
